### ISSUE TITLE
NER Not working properly

### ISSUE THREAD

**Issue by nitishgupta** [CogComp/cogcomp-nlpy#77]
1. SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRISE DEFEAT .
2. CHINA   SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRISE DEFEAT .
3. AL-AIN , United Arab Emirates 1996-12-06

All three sentences get no named entities. Is it because of mentions being in caps?

@danyaljj

**Comment by danyaljj** [comment]
So I tried them in the demo and here is what I see: 
<img width="785" alt="screen shot 2017-09-06 at 10 58 26 am" src="https://user-images.githubusercontent.com/2441454/30126917-6074a440-92f2-11e7-946d-e7bcf74b5f03.png">

So indeed we have to get something. 
Can you try again maybe? There must be a bug somewhere ...

**Comment by nitishgupta** [comment]
I tried again. Still doesn't work. But I (obv.) get the same results are you on the deagol demo server.

**Comment by danyaljj** [comment]
Do you see them when you try the url? 
http://austen.cs.illinois.edu:8080/annotate?text=%22This%20is%20a%20sample%20sentence.%20I%27m%20happy.%22&views=NER_CONLL

**Comment by danyaljj** [comment]
I don't know if you still need this or not. 

I just tried your examples and here is what I get: 
```
NER_CONLL view: (LOC JAPAN) (PER CHINA) (ORG CHINA SOCCER) (LOC JAPAN) (PER CHINA) (LOC AL-AIN) (LOC United Arab Emirates) 
NER_ONTONOTES view: (GPE CHINA) (ORG AL-AIN) (GPE United Arab Emirates 1996-12-06) 
```

Here is my code: 
```python 
        text = """SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRISE DEFEAT . CHINA SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRISE DEFEAT . AL-AIN , United Arab Emirates 1996-12-06. """
        ta = self.lp.doc(text)
        print(ta.get_lemma)
        print(ta.get_ner_conll)
        print(ta.get_ner_ontonotes)
```
