### ISSUE TITLE
NER problem

### ISSUE THREAD

**Issue by sanjayss34** [CogComp/cogcomp-nlpy#80]
I am trying to run NER_ONTONOTES on the following text:

> But we begin tonight with an ongoing mystery . Who is that lone man discovered last month frozen in California 's Sierra Nevada mountains with just a few tantalizing clues to his identity ? This we do know at this hour . The man died more than sixty years ago . He was in the military apparently a World War Two airman . And while it looks like his plane crashed in the mountains so did twenty - five other planes around the same time . Thelma Gutierrez went inside the forensic laboratory where scientists are trying to solve this mystery . An address book a plastic comb a vintage penny . You 're looking at the last things a young airman put into his pockets on the day he died clues to a World War Two cold case that you 're about to see for the very first time . It is a mystery that begins high in the Sierra Nevada Mountains at the bottom of a glacier . Two weeks ago climbers discovered a frozen man face down in the snow still in his army air force uniform and an unopened silk parachute . After six decades the airman is exhumed from his icy tomb and thawed out . but he 's wearing no military dog tags or ID . Did this World War Two pilot perish when his training flight crashed in the mountains like twenty - five other ill fated flights more than sixty years ago ? The search for clues takes us to Honolulu Hawaii to the joint powmia accounting command or jpac . The mystery of the frozen airman is just one of more than a thousand different unsolved cases that scientists here at jpac are trying to solve . In this laboratory alone I 'm surrounded by the remains of at least twenty different service members who are in the process of being identified so that they too can go home . The investigation begins with a team of forensic specialists who probe and study the airman 's bones teeth and his belongings to piece together who he is . And almost immediately clues begin to surface . Dr. Robert Mann a forensic anthropologist has determined that the airman was Caucasian and had fair hair . Next though I 'm going to have to look at his clavicles . The airman 's collar bones and pelvic bones prove that he was in his twenties and died in an airplane crash . This is a person who likely died on impact versus perhaps freezing to death up in the mountains . I think that uh the injuries were so substantial um and severe that he would n't have felt anything . He would have died immediately . One two /- Another important clue . He has a significant number of uh fillings . Like the bones xrays of his wisdom teeth also tell us something about his age . Root tips are closed . they 're sealed up which is more indicative of someone who would be at least twenty - one years old . And Dr. Andy Henry notices something else . The airmen have straight teeth . so he had a nice smile good teeth . Yes I would have to say that yes . Then there are the material clues the things he had on him when he died that offer a snapshot into who he could have been . If there 's a badge or anything else that /- We know he was wearing a World War Two army air force uniform . Remnants of his sweater undergarments and socks are still intact . And more clues emerge from his tattered uniform a corroded nameplate this pin on his collar and this army aircorps insignia . When I found these insignia I was happy to see them . And our young white - haired airman also carried this black comb and some pocket change forty - five cents worth . Some of these dimes are in ranging from nineteen thirty - six to nineteen forty - two . In his uniform breast pocket Dr. Paul Emanovsky found this vintage Schafer pen and three small leatherbound address books . The pages have been decomposing . but could they contain names of friends and loved ones ? And we 're going to put it in a spectral comparator . At first nothing . then like magic clues begin to emerge . Uh you can see all these letters from the calendar Sunday Monday Tuesday up at the top one nine four and two . Nineteen forty - two . Yeah . After hours of meticulous examination of each address book they yield no personal information clues that could have faded with time . And so while we still do not know who our twenty - something fair - haired airman is enormous progress has been made . Out of the thousands of unidentified World War Two service members Dr. Mann says they 've narrowed it down to just ten . So what was it like to grow up there ? In Pleasant Grove we recently met these three sisters all in their eighties who have high hopes that the frozen airman proves to be their big brother Glen Munn whose plane went missing in the Sierra back in nineteen forty - two . Oh I just wanted you know to know that he was found and that we can have him brought home here for burial and /- We do n't know that though . We do n't . but that 's my wishes . And until they learn otherwise they say they will keep that hope alive . And in the weeks and months ahead scientists are convinced they will identify this airman and return him home to his family wherever they might be . Thelma Gutierrez CNN Honolulu Hawaii .

Here is what I get from running `pipeline.call_server(text, "NER_ONTONOTES")` and converting the result to a dictionary (where text is the text above):
{u'corpusId': u'',
 u'id': u'',
 u'sentences': {u'generator': u'UserSpecified',
  u'score': 1.0,
  u'sentenceEndPositions': [1]},
 u'text': u'\xff\xff\xff\xff',
 u'tokenOffsets': [{u'endCharOffset': 4,
   u'form': u'\xff\xff\xff\xff',
   u'startCharOffset': 0}],
 u'tokens': [u'\xff\xff\xff\xff'],
 u'views': [{u'viewData': [{u'generator': u'NER_ONTONOTES-annotator',
     u'score': 1.0,
     u'viewName': u'NER_ONTONOTES',
     u'viewType': u'edu.illinois.cs.cogcomp.core.datastructures.textannotation.SpanLabelView'}],
   u'viewName': u'NER_ONTONOTES'},
  {u'viewData': [{u'constituents': [{u'end': 1,
       u'label': u'',
       u'score': 1.0,
       u'start': 0}],
     u'generator': u'UserSpecified',
     u'score': 1.0,
     u'viewName': u'TOKENS',
     u'viewType': u'edu.illinois.cs.cogcomp.core.datastructures.textannotation.TokenLabelView'}],
   u'viewName': u'TOKENS'}]}

Please note that I am using Python 2.7 in a virtualenv. When I tried using Python 3.4 outside a virtualenv, this worked, but I need to use Python 2.7 for my application. It doesn't work when I try using Python 2.7 outside a virtualenv either. Thank you!
@danyaljj (I'm guessing I should tag you, but please let me know if I shouldn't.)

**Comment by danyaljj** [comment]
Sorry for delay. 

I suppose this is already covered by #81? In which case we should close this. 

Also, I didn't quite get, what was the discrepancy between V2.7 and V3.4. Can you clarify this a bit more?
