### ISSUE TITLE
NER Prediction Issue

### ISSUE THREAD

**Issue by sanjayss34** [CogComp/cogcomp-nlpy#81]
When I run NER_ONTONOTES on the following text through ccg_nlpy.local_pipeline:

> And still ahead on News Night . I carry this little packet my kid gave me . See what my daughter /- Daddy I love you . I miss you . be safe . come home ASAP . Danger on the ground in Iraq and under it . IED Improvised Explosive Devices take a terrible toll . And prison barely dented her popularity . but can Martha Stewart survive her primetime ratings ? Everyday in Iraq US soldiers work very hard to reassure local civilians train the Iraqi army and stay alive . but with the increasing power of Improvised Explosive Devices IEDs staying alive takes a lot of training and time . Eddie Shrahmin is imbedded with American soldiers in northern Bavil province . As the uh informants /- Come here Strovell . listen up please . Like the soldiers he commands Lieutenant Colonel Ross Brown suits up daily trying to rid his area of roadside bombs . Whenever you roll out of the gate and you re out there operating you never know if you re going to hit one of these or not . The first stop today is Route Tampa some of the worst stretch of highway in what is called the Triangle of Death . Salaam Alakum . where these stall owners Brown told are aware of impending attacks . Did you know in advance that the IED was going to go off here ? . Tell him to look me in the eye . . tell me that again . . It is a fine line to walk routing out information without creating new enemies battling an insurgency that kills at will , that turns civilians into accomplices . I think they re scared to death . I think they see us as temporary and they got to live with those people forever . Finding friends locally seems the toughest part of Brown s strategy . but his next task proves just as difficult . Here the Lieutenant Colonel has stopped at one of the firm bases one of the areas that Iraqis are manning their own position . The commander on duty emerges out of uniform . and the Lieutenant colonel struggles to find progress . they did nt do too much work yesterday . They did nt do too much work the day before . They have nt done too much work since they ve been here . . Brown is unsure if this unit can survive an insurgent attack uncertainties shared by the US forces as well each soldier with his own way to cope . Hey Morales you carry anything special with you on missions to help you out ? Well I carry my wedding ring a bracelet my wife sent me /- I carry a Bible Psalms ninety - one . A picture of an angel an archangel . I carry this little packet my kid gave me . See what my daughter /- Daddy I love you . I miss you . be safe . come home ASAP ? Is nt that cool ? All right let s go . Overhead helicopters are responding to an IED attack that moments ago killed Colonel William Wood the highest ranking US officer to die in combat in Iraq a personal friend of Brown s an added personal reason why tomorrow he ll be suiting up again . Eddie Shrahmin CNN northern Bavil Province .

I get the following 'PERSON' mentions:
[u'Stewart survive', u'province', u'suits up', u'are', u'strategy', u'unsure', u'carry', u'ranking US', u'personal']

Is this just because the model is making incorrect predictions, could there be some issue in the Python API, or is it that I am doing something wrong? Right now I am using the result from the pipeline as follows:
`res = json.loads(pipeline.call_server(text, 'NER_ONTONOTES'))`
, where text is the above text. Then I look at each constituent in res['views'][0]['viewData'][0]['constituents'] and if the label of the constituent is equal to 'PERSON', I added it to the list. I get the text for each constituent basically by:
`words = text.split()
for constituent in res['views'][0]['viewData'][0]['constituents'].keys():
    if res['views'][0]['viewData'][0]['constituents'][constituent]['label'] == 'PERSON':
        start = res['views'][0]['viewData'][0]['constituents'][constituent]['start']
        end = res['views'][0]['viewData'][0]['constituents'][constituent]['end']
        print(words[start:end])`

@danyaljj

**Comment by danyaljj** [comment]
I just ran your example and here is what I get: 
```
NER_CONLL view: (LOC Iraq) (PER Martha Stewart) (LOC Iraq) (MISC US) (MISC Iraqi) (PER Eddie Shrahmin) (MISC American) (LOC Bavil) (PER Strovell) (PER Ross Brown) (LOC Route Tampa) (ORG Triangle of Death) (PER Salaam Alakum) (PER Brown) (PER Brown) (MISC Iraqis) (PER Brown) (ORG US forces) (PER Morales) (PER Bible Psalms) (PER William Wood) (LOC US) (LOC Iraq) (PER Brown) (PER Eddie Shrahmin) (ORG Bavil Province) 
Downloading the folder from datastore . . . 
		GroupId: readonly.org.cogcomp.brown-clusters
		ArtifactId: 1.5/brown-clusters.zip
The target /Users/daniel/.cogcomp-datastore/readonly.org.cogcomp.brown-clusters/1.5/brown-clusters already exists. Skipping download from the datastore . . . 
Model file /Users/daniel/ideaProjects/cogcomp-nlpy/tests/ner/models/OntoNotes.model.level1 located in a jar file
Model file /Users/daniel/ideaProjects/cogcomp-nlpy/tests/ner/models/OntoNotes.model.level2 located in a jar file
NER_ONTONOTES view: (WORK_OF_ART News Night) (GPE Iraq) (PERSON Martha Stewart) (GPE Iraq) (GPE US) (NORP Iraqi) (ORG Improvised Explosive Devices) (NORP American) (PERSON Bavil) (PERSON Ross Brown) (CARDINAL one) (ORDINAL first) (DATE today) (LOC the Triangle of Death) (PERSON Brown) (PERSON Brown) (NORP Iraqis) (DATE yesterday) (DATE the day before) (PERSON Brown) (GPE US) (PERSON Morales) (WORK_OF_ART Bible) (WORK_OF_ART Psalms ninety - one) (TIME moments ago) (PERSON William Wood) (GPE US) (GPE Iraq) (PERSON Brown) (DATE tomorrow) (ORG CNN) (GPE Bavil Province) 
```

here is my code: 
```python
        text = """And still ahead on News Night . I carry this little packet my kid gave me . See what my daughter /- Daddy I love you . I miss you . be safe . come home ASAP . Danger on the ground in Iraq and under it . IED Improvised Explosive Devices take a terrible toll . And prison barely dented her popularity . but can Martha Stewart survive her primetime ratings ? Everyday in Iraq US soldiers work very hard to reassure local civilians train the Iraqi army and stay alive . but with the increasing power of Improvised Explosive Devices IEDs staying alive takes a lot of training and time . Eddie Shrahmin is imbedded with American soldiers in northern Bavil province . As the uh informants /- Come here Strovell . listen up please . Like the soldiers he commands Lieutenant Colonel Ross Brown suits up daily trying to rid his area of roadside bombs . Whenever you roll out of the gate and you re out there operating you never know if you re going to hit one of these or not . The first stop today is Route Tampa some of the worst stretch of highway in what is called the Triangle of Death . Salaam Alakum . where these stall owners Brown told are aware of impending attacks . Did you know in advance that the IED was going to go off here ? . Tell him to look me in the eye . . tell me that again . . It is a fine line to walk routing out information without creating new enemies battling an insurgency that kills at will , that turns civilians into accomplices . I think they re scared to death . I think they see us as temporary and they got to live with those people forever . Finding friends locally seems the toughest part of Brown s strategy . but his next task proves just as difficult . Here the Lieutenant Colonel has stopped at one of the firm bases one of the areas that Iraqis are manning their own position . The commander on duty emerges out of uniform . and the Lieutenant colonel struggles to find progress . they did nt do too much work yesterday . They did nt do too much work the day before . They have nt done too much work since they ve been here . . Brown is unsure if this unit can survive an insurgent attack uncertainties shared by the US forces as well each soldier with his own way to cope . Hey Morales you carry anything special with you on missions to help you out ? Well I carry my wedding ring a bracelet my wife sent me /- I carry a Bible Psalms ninety - one . A picture of an angel an archangel . I carry this little packet my kid gave me . See what my daughter /- Daddy I love you . I miss you . be safe . come home ASAP ? Is nt that cool ? All right let s go . Overhead helicopters are responding to an IED attack that moments ago killed Colonel William Wood the highest ranking US officer to die in combat in Iraq a personal friend of Brown s an added personal reason why tomorrow he ll be suiting up again . Eddie Shrahmin CNN northern Bavil Province ."""
        ta = self.lp.doc(text)
        print(ta.get_lemma)
        print(ta.get_ner_conll)
        print(ta.get_ner_ontonotes)
```


They all look correct to me. If the issue still stands, please re-open this.
