### ISSUE TITLE
Local_PIpeline: why protobuff?

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlpy#89]
@GHLgh @bhargav you guys remember why we are writing the output of the remote server into a proobuff file and then read it again? (instead of just returning the json output of the server). 
https://github.com/CogComp/cogcomp-nlpy/blob/master/ccg_nlpy/local_pipeline.py#L70-L77

I have one guess, but I am not sure if it is correct: it is possible that we are not able to read the output of the java code directly, so we have to write it on disk, and read it again. Is that correct?

**Comment by GHLgh** [comment]
Actually the Python side can read the JSON serialization from Java code, but you are right that Protobuf was used for cross-platform purpose.

For this particular part, I found the conversation in #47: SerializatuinHelper will print the JSON result, so there will be redundant output. It would be faster to call `serializeToJson` directly but not user-friendly.
